### ISSUE TITLE
view in theme

### ISSUE THREAD

**Issue by Ehsan1733** [kevinruscoe/acf-star-rating#14]
how to star show in wordpress theme?

**Comment by JayHoltslander** [comment]
![](https://media.giphy.com/media/H6KRGhgRMbBwA/giphy.gif)

**Comment by JeyKeu** [comment]
Did anyone figure out how to use this? please do share

**Comment by RonR-WebDesign** [comment]
Yes, please tell us the secret!  It works as a custom field to add the number of stars but how do you display them on a page (...the stars, I know how to display all the other meta fields).

**Comment by odil-io** [comment]
It's simple, use the_field('fieldname'); where ever you want to post **any** field from ACF..

**Comment by kevdotbadger** [comment]
Just get the value of the stars saved `get_field('rating')`, then in your template loop that many times and print stars, hearts, things as you want. This field is just a nicer looking number field.
