### ISSUE TITLE
Front-end view?

### ISSUE THREAD

**Issue by benjino** [kevinruscoe/acf-star-rating#18]
How is this supposed to show on the front end?
With the label and five stars below it?
I've gotten it to work in ACF, to show in a CPT, but am not clear on how it will present on the front-end?

**Comment by kevdotbadger** [comment]
This is simply a nicer looking number field. On the front end, the idea is you simply loop up to the field-value (i.e. 4) and print stars (or hearts, or whatever).

**Comment by benjino** [comment]
Yah, finally got it working, it's been very good for me!
